name: HTML to APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '30'
        build-tools: '30.0.3'

    - name: Create necessary directories
      run: |
        mkdir -p AndroidTest/res/drawable
        mkdir -p AndroidTest/res/values
        mkdir -p AndroidTest/src/com/tt/rnd
        mkdir -p AndroidTest/assets

    - name: Copy HTML file
      run: cp index.html AndroidTest/assets/

    - name: Generate keystore
      run: |
        keytool -genkeypair -validity 10000 -dname "CN=company name, OU=organisational unit, O=organisation, L=location, S=state, C=country code" -keystore AndroidTest.keystore -storepass password -keypass password -alias AndroidTestKey2 -keyalg RSA -v

    - name: Generate R.java
      run: |
        $ANDROID_HOME/build-tools/30.0.3/aapt package -v -f -m -S AndroidTest/res -J AndroidTest/src -M AndroidTest/AndroidManifest.xml -I $ANDROID_HOME/platforms/android-30/android.jar

    - name: Compile Java code
      run: |
        javac -verbose -d AndroidTest/obj -classpath $ANDROID_HOME/platforms/android-30/android.jar:AndroidTest/obj -sourcepath AndroidTest/src AndroidTest/src/com/tt/rnd/*.java

    - name: Create DEX file
      run: |
        $ANDROID_HOME/build-tools/30.0.3/dx --dex --verbose --output=AndroidTest/bin/classes.dex AndroidTest/obj AndroidTest/lib

    - name: Create unsigned APK file
      run: |
        $ANDROID_HOME/build-tools/30.0.3/aapt package -v -f -A AndroidTest/assets -M AndroidTest/AndroidManifest.xml -S AndroidTest/res -I $ANDROID_HOME/platforms/android-30/android.jar -F AndroidTest/bin/AndroidTest.unsigned.apk AndroidTest/bin

    - name: Sign APK file
      run: |
        jarsigner -verbose -keystore AndroidTest.keystore -storepass password -keypass password -signedjar AndroidTest/bin/AndroidTest.signed.apk AndroidTest/bin/AndroidTest.unsigned.apk AndroidTestKey2

    - name: Zip-align APK file
      run: |
        $ANDROID_HOME/build-tools/30.0.3/zipalign -v 4 AndroidTest/bin/AndroidTest.signed.apk AndroidTest/bin/AndroidTest.apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: AndroidTest APK
        path: AndroidTest/bin/AndroidTest.apk
